import {randomUUID} from 'node:crypto';
import {creditDemoCredits,debitDemoCredits,getPublicPlayer} from './player-store.js';

const tournaments=new Map();
const customSizes=new Set([8,16,32,64,128]);
const validFormats=new Set(['qualifier','knockout','hybrid']);
const productRules={sprint:{minPlayers:32,maxPlayers:64,idealPlayers:64,entryCents:1_000,countdownMs:180_000,format:'hybrid'},master:{minPlayers:16,maxPlayers:24,idealPlayers:20,entryCents:5_000,countdownMs:300_000,format:'hybrid'}};

function roundName(totalPlayers,roundIndex,totalRounds){if(roundIndex===totalRounds-1)return 'Final';if(roundIndex===totalRounds-2)return 'Semifinal';if(totalPlayers/(2**roundIndex)===8)return 'Quartas de final';return `Rodada ${roundIndex+1}`;}
function buildBracket(size){if(size<2||(size&(size-1))!==0)throw new Error('A fase mata-mata exige potência de dois.');const totalRounds=Math.log2(size),rounds=[];for(let roundIndex=0;roundIndex<totalRounds;roundIndex++){const matchCount=size/(2**(roundIndex+1));rounds.push({index:roundIndex,name:roundName(size,roundIndex,totalRounds),matches:Array.from({length:matchCount},(_,index)=>({id:randomUUID(),index,playerIds:[null,null],winnerId:null,loserId:null,status:'waiting'}))});}return {rounds,thirdPlace:{id:randomUUID(),playerIds:[null,null],winnerId:null,loserId:null,status:'waiting'}};}

export function calculateTournamentPreview({participants,entryCents,commissionPercent=15,distribution={first:55,second:30,third:15}}){if(!Number.isInteger(participants)||participants<0||!Number.isInteger(entryCents)||entryCents<0)throw new Error('Participantes e entrada devem ser inteiros.');if(Object.values(distribution).reduce((sum,value)=>sum+value,0)!==100)throw new Error('O pódio deve somar 100%.');const grossPotCents=participants*entryCents,commissionCents=Math.floor(grossPotCents*commissionPercent/100),prizePoolCents=grossPotCents-commissionCents,first=Math.floor(prizePoolCents*distribution.first/100),second=Math.floor(prizePoolCents*distribution.second/100);return {participants,entryCents,grossPotCents,commissionPercent,commissionCents,prizePoolCents,prizes:{first,second,third:prizePoolCents-first-second}};}

function publicTournament(t){const preview=calculateTournamentPreview({participants:t.players.length,entryCents:t.entryCents,commissionPercent:t.commissionPercent,distribution:t.prizeDistribution});return {id:t.id,name:t.name,kind:t.kind,size:t.maxPlayers,minPlayers:t.minPlayers,maxPlayers:t.maxPlayers,idealPlayers:t.idealPlayers,mode:t.mode,language:t.language,format:t.format,status:t.status,entryCredits:t.entryCredits,entryCents:t.entryCents,commissionPercent:t.commissionPercent,prizeDistribution:t.prizeDistribution,virtualPrizePool:t.virtualPrizePool,sponsoredPrizeCents:t.sponsoredPrizeCents,startsAt:t.startsAt,countdownStartsAt:t.countdownStartsAt,minimumReached:t.players.length>=t.minPlayers,missingMinimum:Math.max(0,t.minPlayers-t.players.length),recurrence:t.recurrence,players:t.players.map(id=>getPublicPlayer(id)).filter(Boolean),financialPreview:preview,bracket:t.bracket,qualifyingRounds:t.qualifyingRounds,podium:t.podium,history:t.history};}

export function createTournament(input={}){const kind=['sprint','master'].includes(input.kind)?input.kind:'custom',rule=productRules[kind];let maxPlayers=Number(input.maxPlayers||input.size||rule?.maxPlayers||8),minPlayers=Number(input.minPlayers||rule?.minPlayers||maxPlayers),idealPlayers=Number(input.idealPlayers||rule?.idealPlayers||maxPlayers),entryCents=Number(input.entryCents??rule?.entryCents??0),format=input.format||rule?.format||'knockout';if(kind==='custom'&&!customSizes.has(maxPlayers))throw new Error('Torneios personalizados aceitam 8, 16, 32, 64 ou 128 jogadores.');if(kind==='sprint'&&(minPlayers!==32||maxPlayers!==64))throw new Error('Sprint usa mínimo 32 e máximo 64 jogadores.');if(kind==='master'&&(minPlayers<16||maxPlayers>24||idealPlayers<minPlayers||idealPlayers>maxPlayers))throw new Error('Master usa mínimo 16, ideal 20 e máximo 24 jogadores.');if(!validFormats.has(format))throw new Error('Formato de torneio inválido.');if(!['quarteto','contexto'].includes(input.mode||'quarteto'))throw new Error('Modo de torneio inválido.');if(!Number.isInteger(entryCents)||entryCents<0)throw new Error('Entrada financeira inválida.');const entryCredits=Number(input.entryCredits||0),commissionPercent=Number(input.commissionPercent??15),gross=maxPlayers*entryCredits,virtualPrizePool=Math.floor(gross*(100-commissionPercent)/100),id=randomUUID();const tournament={id,name:String(input.name||`${kind==='sprint'?'Sprint':kind==='master'?'Master':'Arena'} ${maxPlayers}`).slice(0,80),kind,mode:input.mode||'quarteto',language:input.language||'pt',format,minPlayers,maxPlayers,idealPlayers,entryCredits,entryCents,commissionPercent,prizeDistribution:{first:55,second:30,third:15},virtualPrizePool,sponsoredPrizeCents:Number(input.sponsoredPrizeCents||0),startsAt:Number(input.startsAt||Date.now()),countdownMs:Number(input.countdownMs||rule?.countdownMs||0),countdownStartsAt:null,status:'registration',recurrence:input.recurrence||null,players:[],bracket:format==='knockout'?buildBracket(maxPlayers):null,qualifyingRounds:[],podium:null,history:[],createdAt:new Date().toISOString()};tournaments.set(id,tournament);return publicTournament(tournament);}

export function createSprintTournament({mode='quarteto',language='pt',sequence=1}={}){return createTournament({kind:'sprint',name:`${mode.toUpperCase()} SPRINT #${sequence}`,mode,language});}
export function createMasterTournament({mode='quarteto',language='pt',name=`${mode.toUpperCase()} MASTER`}={}){return createTournament({kind:'master',name,mode,language});}
export function joinTournament(tournamentId,playerId){const t=tournaments.get(tournamentId);if(!t)throw new Error('Torneio não encontrado.');if(t.status!=='registration')throw new Error('As inscrições deste torneio foram encerradas.');if(t.players.includes(playerId))throw new Error('Jogador já inscrito neste torneio.');if(t.players.length>=t.maxPlayers)throw new Error('Torneio lotado.');if(!getPublicPlayer(playerId))throw new Error('Jogador não encontrado.');if(t.entryCredits>0)debitDemoCredits(playerId,t.entryCredits,{type:'tournament_entry',tournamentId,description:`Inscrição virtual: ${t.name}`});t.players.push(playerId);t.history.push({type:'joined',playerId,at:new Date().toISOString()});if(t.players.length===t.minPlayers&&t.minPlayers<t.maxPlayers){t.countdownStartsAt=Date.now()+t.countdownMs;t.history.push({type:'minimum_reached',startsAt:t.countdownStartsAt,at:new Date().toISOString()});}if(t.players.length===t.maxPlayers)startTournament(t.id);return publicTournament(t);}
export function tickTournaments(now=Date.now()){const started=[];for(const t of tournaments.values())if(t.status==='registration'&&t.players.length>=t.minPlayers&&t.countdownStartsAt&&t.countdownStartsAt<=now){startTournament(t.id);started.push(t.id);}return started;}
export function startTournament(tournamentId){const t=tournaments.get(tournamentId);if(!t||t.status!=='registration')throw new Error('Torneio disponível para início não encontrado.');if(t.players.length<t.minPlayers)throw new Error(`São necessários ao menos ${t.minPlayers} jogadores reais.`);t.status='active';t.startsAt=Date.now();if(t.format==='knockout'){t.bracket=buildBracket(t.players.length);seedBracket(t,t.players);}else createTournamentRound(t.id,{advanceCount:t.kind==='sprint'?Math.min(32,t.players.length):Math.min(16,2**Math.floor(Math.log2(t.players.length)))});t.history.push({type:'started',at:new Date().toISOString()});if(t.kind==='sprint')ensureNextSprint(t);return publicTournament(t);}
function ensureNextSprint(started){const open=[...tournaments.values()].some(t=>t.kind==='sprint'&&t.mode===started.mode&&t.status==='registration');if(open)return;const numbers=[...tournaments.values()].filter(t=>t.kind==='sprint'&&t.mode===started.mode).map(t=>Number(t.name.match(/#(\d+)/)?.[1]||0));createSprintTournament({mode:started.mode,language:started.language,sequence:Math.max(0,...numbers)+1});}
function seedBracket(t,playerIds){t.bracket.rounds[0].matches.forEach((match,index)=>{match.playerIds=[playerIds[index*2],playerIds[index*2+1]];match.status='ready';});}
export function createTournamentRound(tournamentId,{advanceCount}={}){const t=tournaments.get(tournamentId);if(!t||t.status!=='active')throw new Error('Torneio ativo não encontrado.');const playerIds=[...(t.qualifyingRounds.at(-1)?.qualifiedIds||t.players)],safeAdvance=Math.max(2,Math.min(Number(advanceCount)||2,playerIds.length));const round={id:randomUUID(),index:t.qualifyingRounds.length,status:'active',seed:randomUUID(),playerIds,advanceCount:safeAdvance,results:[],qualifiedIds:[]};t.qualifyingRounds.push(round);t.history.push({type:'round_started',roundId:round.id,at:new Date().toISOString()});return structuredClone(round);}
export function submitTournamentRoundResult(tournamentId,roundId,playerId,result){const t=tournaments.get(tournamentId),round=t?.qualifyingRounds.find(item=>item.id===roundId);if(!round||round.status!=='active'||!round.playerIds.includes(playerId))throw new Error('Rodada classificatória ativa não encontrada.');if(round.results.some(item=>item.playerId===playerId))throw new Error('Resultado já enviado.');const safe=t.mode==='quarteto'?{playerId,solved:Number(result.solved)||0,elapsedMs:Number(result.elapsedMs)||Infinity,attempts:Number(result.attempts)||Infinity}:{playerId,discovered:Boolean(result.discovered),elapsedMs:Number(result.elapsedMs)||Infinity,attempts:Number(result.attempts)||Infinity,bestRank:Number(result.bestRank)||9999};round.results.push(safe);return structuredClone(safe);}
function compareRound(mode,a,b){if(mode==='quarteto')return b.solved-a.solved||a.elapsedMs-b.elapsedMs||a.attempts-b.attempts||a.playerId.localeCompare(b.playerId);return Number(b.discovered)-Number(a.discovered)||(a.discovered?a.elapsedMs-b.elapsedMs:a.bestRank-b.bestRank)||a.attempts-b.attempts||a.playerId.localeCompare(b.playerId);}
export function advanceTournamentRound(tournamentId,roundId){const t=tournaments.get(tournamentId),round=t?.qualifyingRounds.find(item=>item.id===roundId);if(!round||round.status!=='active')throw new Error('Rodada ativa não encontrada.');if(round.results.length!==round.playerIds.length)throw new Error('A rodada ainda possui jogadores sem resultado.');round.results.sort((a,b)=>compareRound(t.mode,a,b));round.qualifiedIds=round.results.slice(0,round.advanceCount).map(item=>item.playerId);round.status='completed';t.history.push({type:'round_completed',roundId,qualifiedIds:round.qualifiedIds,at:new Date().toISOString()});if(t.format==='hybrid'&&round.qualifiedIds.length<=8&&(round.qualifiedIds.length&(round.qualifiedIds.length-1))===0){t.bracket=buildBracket(round.qualifiedIds.length);seedBracket(t,round.qualifiedIds);}else if(t.format==='qualifier'&&round.qualifiedIds.length<=2){t.podium={first:round.qualifiedIds[0],second:round.qualifiedIds[1],third:round.results[2]?.playerId||null};finishTournament(t);}return publicTournament(t);}
function findBracketMatch(t,matchId){for(const round of t.bracket?.rounds||[]){const match=round.matches.find(item=>item.id===matchId);if(match)return {match,round};}if(t.bracket?.thirdPlace.id===matchId)return {match:t.bracket.thirdPlace,round:{index:'third'}};return null;}
export function recordTournamentResult(tournamentId,matchId,winnerId){const t=tournaments.get(tournamentId);if(!t||t.status!=='active')throw new Error('Torneio ativo não encontrado.');const found=findBracketMatch(t,matchId);if(!found)throw new Error('Confronto não encontrado.');const {match,round}=found;if(match.status==='finished')throw new Error('Confronto já finalizado.');if(!match.playerIds.includes(winnerId)||match.playerIds.some(id=>!id))throw new Error('Vencedor inválido para este confronto.');match.winnerId=winnerId;match.loserId=match.playerIds.find(id=>id!==winnerId);match.status='finished';t.history.push({type:'match_finished',matchId,winnerId,at:new Date().toISOString()});if(round.index==='third'){completeTournamentIfReady(t);return publicTournament(t);}const nextRound=t.bracket.rounds[round.index+1];if(nextRound){const next=nextRound.matches[Math.floor(match.index/2)];next.playerIds[match.index%2]=winnerId;if(next.playerIds.every(Boolean))next.status='ready';if(round.name==='Semifinal'){const third=t.bracket.thirdPlace;third.playerIds[match.index]=match.loserId;if(third.playerIds.every(Boolean))third.status='ready';}}completeTournamentIfReady(t);return publicTournament(t);}
function completeTournamentIfReady(t){const final=t.bracket.rounds.at(-1).matches[0],third=t.bracket.thirdPlace;if(final.status!=='finished'||third.status!=='finished')return;t.podium={first:final.winnerId,second:final.loserId,third:third.winnerId};finishTournament(t);}
function finishTournament(t){t.status='completed';if(t.virtualPrizePool>0){const first=Math.floor(t.virtualPrizePool*.55),second=Math.floor(t.virtualPrizePool*.30),awards={first,second,third:t.virtualPrizePool-first-second};for(const [place,amount] of Object.entries(awards)){const playerId=t.podium?.[place];if(playerId)creditDemoCredits(playerId,amount,{type:'tournament_prize',tournamentId:t.id,description:`${place} lugar — prêmio virtual`});}}t.history.push({type:'completed',podium:t.podium,at:new Date().toISOString()});}
export function getTournament(id){const t=tournaments.get(id);return t?publicTournament(t):null;}
export function listTournaments(){tickTournaments();return [...tournaments.values()].map(publicTournament).sort((a,b)=>(a.status==='registration'?-1:1)-(b.status==='registration'?-1:1)||a.startsAt-b.startsAt);}
export function resetTournaments(){tournaments.clear();}
export function ensureProductTournaments(){
  if(![...tournaments.values()].some(t=>t.kind==='sprint'&&t.mode==='quarteto'&&t.status==='registration'))createSprintTournament({mode:'quarteto',sequence:1});
  if(![...tournaments.values()].some(t=>t.kind==='master'&&t.mode==='contexto'&&t.status==='registration'))createMasterTournament({mode:'contexto'});
  return listTournaments();
}
